// src/actions/types.js

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_CERTIFICATES = 'GET_CERTIFICATES';
export const CERTIFICATES_ERROR = 'CERTIFICATES_ERROR';
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';  // New action type
export const FETCH_FOLLOWED_CATEGORIES_SUCCESS = 'FETCH_FOLLOWED_CATEGORIES_SUCCESS'; // New action type
export const ACCEPT_POLICY_SUCCESS = 'ACCEPT_POLICY_SUCCESS'; // New action type

// actionTypes.js

export const FETCH_NOTIFICATIONS_SUCCESS = 'FETCH_NOTIFICATIONS_SUCCESS';
export const ADD_NOTIFICATION_SUCCESS = 'ADD_NOTIFICATION_SUCCESS';
export const MARK_NOTIFICATION_AS_READ_SUCCESS = 'MARK_NOTIFICATION_AS_READ_SUCCESS';
export const FOLLOW_CATEGORY_SUCCESS = 'FOLLOW_CATEGORY_SUCCESS';
export const UNFOLLOW_CATEGORY_SUCCESS = 'UNFOLLOW_CATEGORY_SUCCESS';
