// src/actions/types.js

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const GET_CERTIFICATES = 'GET_CERTIFICATES';
export const CERTIFICATES_ERROR = 'CERTIFICATES_ERROR';